# Generated by Django 6.0.7 on 2026-07-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(default='Nama Sekolah', max_length=100)),
                ('sejarah', models.TextField(help_text='Tuliskan sejarah singkat sekolah')),
                ('visi', models.TextField()),
                ('misi', models.TextField(help_text='Gunakan enter untuk memisahkan setiap poin misi')),
            ],
        ),
    ]
