# Generated by Django 6.0.7 on 2026-07-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_profilsekolah'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guru',
            options={'ordering': ['urutan', 'nama']},
        ),
        migrations.AddField(
            model_name='guru',
            name='urutan',
            field=models.IntegerField(default=99, help_text='1 untuk Kepala Sekolah, 2 Wakil, 3 Guru, dst.'),
        ),
    ]
