# Generated by Django 6.0.7 on 2026-07-19 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_alter_guru_options_guru_urutan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='isi_berita',
            new_name='isi',
        ),
        migrations.RenameField(
            model_name='berita',
            old_name='tanggal_dibuat',
            new_name='tanggal_upload',
        ),
        migrations.AddField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='berita/'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
