# Generated by Django 6.0.7 on 2026-07-21 13:57

import sekolah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_rename_isi_berita_berita_isi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Selamat Datang', help_text='Teks kecil di atas judul (contoh: Selamat Datang / Official Website)', max_length=50)),
                ('judul', models.CharField(default='SD YWKA REL HOMY SCHOOL', max_length=200)),
                ('isi', models.TextField(help_text='Deskripsi atau teks paragraf di bawah judul')),
                ('gambar', models.ImageField(blank=True, help_text='Biarkan kosong jika ingin pakai background gradasi warna', null=True, upload_to='hero/')),
                ('link', models.CharField(default='/profil', help_text='Link tujuan saat tombol diklik', max_length=200)),
                ('teks_tombol', models.CharField(default='Mulai Mengenal Kami', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Centang untuk menampilkan banner ini')),
            ],
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=sekolah.models.ubah_nama_gambar_acak),
        ),
    ]
