# Generated by Django 6.0.7 on 2026-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0005_herobanner_alter_berita_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Contoh: Religius (REL)', max_length=50)),
                ('deskripsi', models.TextField()),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('icon_svg', models.TextField(blank=True, help_text='Paste path SVG dari heroicons.com (opsional)', null=True)),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='StrukturOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Yayasan & Komite', 'Pimpinan Yayasan & Komite'), ('Manajemen Sekolah', 'Pimpinan & Manajemen Sekolah')], max_length=50)),
                ('jabatan', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('urutan', models.IntegerField(default=0, help_text='Angka terkecil tampil lebih dulu')),
            ],
            options={
                'ordering': ['kategori', 'urutan'],
            },
        ),
    ]
