# Generated by Django 6.0.7 on 2026-07-22 10:18

import sekolah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_corevalue_fasilitas_strukturorganisasi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreValue',
        ),
        migrations.DeleteModel(
            name='Fasilitas',
        ),
        migrations.DeleteModel(
            name='StrukturOrganisasi',
        ),
        migrations.AlterModelOptions(
            name='guru',
            options={'ordering': ['role', 'nama'], 'verbose_name': 'SDM (Guru & Staf)', 'verbose_name_plural': 'Data SDM (Guru & Staf)'},
        ),
        migrations.RemoveField(
            model_name='guru',
            name='urutan',
        ),
        migrations.AddField(
            model_name='guru',
            name='badge_color',
            field=models.CharField(default='bg-blue-900 text-amber-300', help_text='Class Tailwind untuk warna badge (contoh: bg-blue-900 text-amber-300)', max_length=100),
        ),
        migrations.AddField(
            model_name='guru',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=sekolah.models.ubah_nama_foto_sdm),
        ),
        migrations.AddField(
            model_name='guru',
            name='kategori',
            field=models.CharField(choices=[('Pimpinan', 'Pimpinan (Kepala/Wakil Sekolah)'), ('Wali Kelas', 'Wali Kelas'), ('Guru Mata Pelajaran', 'Guru Mata Pelajaran'), ('Tahsin & Tahfidz', 'Tahsin & Tahfidz'), ('Staf & TU', 'Staf & Tata Usaha'), ('Office Boy', 'Office Boy (OB)')], default='Guru Mata Pelajaran', max_length=50),
        ),
        migrations.AddField(
            model_name='guru',
            name='mapel',
            field=models.CharField(blank=True, help_text='Mata pelajaran / Bidang tugas', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='motto',
            field=models.TextField(blank=True, help_text='Motto atau kutipan kerja', null=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='role',
            field=models.IntegerField(default=1, help_text='Urutan ID/Role: 1 (Kepala Sekolah), 2 (Wakil/Koordinator), dst.'),
        ),
        migrations.AlterField(
            model_name='guru',
            name='jabatan',
            field=models.CharField(help_text='Contoh: Kepala Sekolah, Wali Kelas 1A, dll', max_length=100),
        ),
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(blank=True, help_text='NIP / NIY pegawai', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='link',
            field=models.CharField(default='/profil', max_length=200),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='tag',
            field=models.CharField(default='Selamat Datang', help_text='Teks kecil di atas judul', max_length=50),
        ),
    ]
