# Generated by Django 6.0.7 on 2026-07-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_delete_corevalue_delete_fasilitas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='asal_kampus',
            field=models.CharField(blank=True, help_text='Contoh: Universitas Pasundan, UPI, dll', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='gelar',
            field=models.CharField(blank=True, help_text='Contoh: S.T., S.Kom., M.Pd.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, help_text='Contoh: S1, S2, D3', max_length=50, null=True),
        ),
    ]
