# Generated by Django 6.0.7 on 2026-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0008_guru_asal_kampus_guru_gelar_guru_pendidikan_terakhir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'ordering': ['-tanggal_upload'], 'verbose_name': 'Berita & Kegiatan', 'verbose_name_plural': 'Data Berita & Kegiatan'},
        ),
        migrations.AddField(
            model_name='berita',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Tandai sebagai berita utama (headline)'),
        ),
        migrations.AddField(
            model_name='berita',
            name='kategori',
            field=models.CharField(choices=[('Kegiatan Siswa', 'Kegiatan Siswa'), ('Prestasi', 'Prestasi'), ('Akademik', 'Akademik'), ('Pengumuman', 'Pengumuman')], default='Kegiatan Siswa', max_length=50),
        ),
        migrations.AddField(
            model_name='berita',
            name='ringkasan',
            field=models.TextField(blank=True, help_text='Ringkasan singkat untuk ditampilkan di kartu berita', null=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='isi',
            field=models.TextField(help_text='Isi berita lengkap (mendukung HTML / Rich Text)'),
        ),
    ]
