# Generated by Django 6.0.7 on 2026-07-22 15:45

import datetime
import sekolah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0009_alter_berita_options_berita_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengumuman',
            options={'ordering': ['-is_pinned', '-tanggal', '-tanggal_dibuat'], 'verbose_name': 'Pengumuman', 'verbose_name_plural': 'Data Pengumuman'},
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Tandai sebagai pengumuman disematkan (pinned)'),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='kategori',
            field=models.CharField(choices=[('Surat Edaran', 'Surat Edaran'), ('Akademik & Ujian', 'Akademik & Ujian'), ('Kegiatan', 'Kegiatan'), ('Keuangan', 'Keuangan')], default='Surat Edaran', max_length=50),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='lampiran',
            field=models.FileField(blank=True, help_text='File lampiran PDF (opsional)', null=True, upload_to=sekolah.models.ubah_nama_file_pengumuman),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='prioritas',
            field=models.CharField(choices=[('Mendesak', 'Mendesak'), ('Penting', 'Penting'), ('Biasa', 'Biasa')], default='Biasa', max_length=20),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='ringkasan',
            field=models.TextField(blank=True, help_text='Ringkasan singkat untuk kartu pengumuman', null=True),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='tanggal',
            field=models.DateField(default=datetime.date(2026, 7, 22), help_text='Tanggal pengumuman diterbitkan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='target',
            field=models.CharField(default='Wali Murid & Siswa', help_text='Target pembaca/audiens', max_length=150),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='isi_pengumuman',
            field=models.TextField(help_text='Isi pengumuman lengkap'),
        ),
    ]
