# Generated by Django 6.0.7 on 2026-07-22 16:27

import django.db.models.deletion
import sekolah.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0010_alter_pengumuman_options_pengumuman_is_pinned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumGaleri',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('Prestasi & Lomba', 'Prestasi & Lomba'), ('MPLS & Orientasi', 'MPLS & Orientasi'), ('Keagamaan', 'Keagamaan'), ('Ekskul & Seni', 'Ekskul & Seni')], default='Prestasi & Lomba', max_length=50)),
                ('tanggal', models.DateField(help_text='Tanggal kegiatan album')),
                ('cover', models.ImageField(blank=True, help_text='Foto sampul album', null=True, upload_to='galeri/cover/')),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi singkat album kegiatan', null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Album Galeri Foto',
                'verbose_name_plural': 'Data Album Galeri Foto',
                'ordering': ['-tanggal', '-tanggal_upload'],
            },
        ),
        migrations.CreateModel(
            name='FotoAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gambar', models.ImageField(upload_to=sekolah.models.ubah_nama_foto_album)),
                ('keterangan', models.CharField(blank=True, help_text='Keterangan opsional untuk foto ini', max_length=255, null=True)),
                ('album', models.ForeignKey(help_text='Pilih album induk', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='sekolah.albumgaleri')),
            ],
            options={
                'verbose_name': 'Foto Item Album',
                'verbose_name_plural': 'Data Foto Item Album',
            },
        ),
        migrations.CreateModel(
            name='VideoGaleri',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('Prestasi & Lomba', 'Prestasi & Lomba'), ('MPLS & Orientasi', 'MPLS & Orientasi'), ('Keagamaan', 'Keagamaan'), ('Ekskul & Seni', 'Ekskul & Seni')], default='MPLS & Orientasi', max_length=50)),
                ('tanggal', models.DateField(help_text='Tanggal video diterbitkan')),
                ('embed_url', models.URLField(help_text='URL Embed YouTube (contoh: https://www.youtube.com/embed/...)')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Dokumentasi',
                'verbose_name_plural': 'Data Video Dokumentasi',
                'ordering': ['-tanggal', '-tanggal_upload'],
            },
        ),
        migrations.DeleteModel(
            name='Galeri',
        ),
    ]
