# Generated by Django 6.0.7 on 2026-07-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0011_albumgaleri_fotoalbum_videogaleri_delete_galeri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Akun user Django yang terhubung dengan data SDM ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guru_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guru',
            name='badge_color',
            field=models.CharField(default='bg-blue-900 text-amber-300', help_text='Class Tailwind untuk warna badge', max_length=100),
        ),
        migrations.AlterField(
            model_name='guru',
            name='motto',
            field=models.TextField(blank=True, help_text='Motto atau kutipan kerja (ditampilkan juga di halaman Guest)', null=True),
        ),
    ]
