# Generated by Django 6.0.7 on 2026-07-25 07:28

import django.db.models.deletion
import sekolah.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0012_guru_user_alter_guru_badge_color_alter_guru_motto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_profil', models.ImageField(blank=True, help_text='Foto profil akun (avatar)', null=True, upload_to=sekolah.models.ubah_nama_foto_profil)),
                ('user', models.OneToOneField(help_text='Akun user Django yang terhubung dengan profil ini', on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
