# Generated by Django 6.0.7 on 2026-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='motto',
            field=models.TextField(blank=True, help_text='Motto atau quotes pribadi user', null=True),
        ),
    ]
