# Generated by Django 6.0.7 on 2026-07-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0014_userprofile_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role_type',
            field=models.CharField(choices=[('guru', 'Guru / Pengajar'), ('staf', 'Staf / Tata Usaha'), ('user', 'User Biasa')], default='guru', help_text='Role portal sekunder pengguna', max_length=20),
        ),
    ]
