# Generated by Django 6.0.7 on 2026-07-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0015_userprofile_role_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='penulis',
            field=models.ForeignKey(blank=True, help_text='User/Penulis yang mengunggah berita ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
