# Generated by Django 6.0.7 on 2026-07-27 16:40

import sekolah.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0016_berita_penulis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('Akademik', 'Akademik & Ujian'), ('Keagamaan', 'Keagamaan & PHBI'), ('Seni & Olahraga', 'Seni & Olahraga'), ('Peringatan Hari Besar', 'Peringatan Hari Besar'), ('Rapat & Pertemuan', 'Rapat & Pertemuan'), ('Lainnya', 'Lainnya')], default='Akademik', max_length=50)),
                ('status', models.CharField(choices=[('Akan Datang', 'Akan Datang'), ('Berlangsung', 'Berlangsung'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Akan Datang', max_length=30)),
                ('tanggal_mulai', models.DateField(help_text='Tanggal mulai acara')),
                ('tanggal_selesai', models.DateField(blank=True, help_text='Tanggal selesai (opsional jika 1 hari)', null=True)),
                ('waktu', models.CharField(default='08:00 WIB - Selesai', help_text='Contoh: 08:00 - 12:00 WIB', max_length=100)),
                ('lokasi', models.CharField(default='SD YWKA', help_text='Lokasi / Tempat Acara', max_length=200)),
                ('penyelenggara', models.CharField(default='SD YWKA', help_text='Penyelenggara / Panitia Acara', max_length=150)),
                ('ringkasan', models.TextField(blank=True, help_text='Ringkasan singkat untuk kartu acara', null=True)),
                ('deskripsi', models.TextField(help_text='Deskripsi lengkap / susunan acara')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=sekolah.models.ubah_nama_poster_event)),
                ('link_pendaftaran', models.URLField(blank=True, help_text='Link pendaftaran / Google Form (opsional)', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Tandai sebagai acara utama / unggulan')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event & Acara',
                'verbose_name_plural': 'Data Event & Acara',
                'ordering': ['-tanggal_mulai', '-tanggal_dibuat'],
            },
        ),
    ]
