# Generated by Django 6.0.7 on 2026-08-08 16:05

import sekolah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0019_alter_post_gambar_note_notelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumgaleri',
            name='cover',
            field=models.ImageField(blank=True, help_text='Foto sampul album', null=True, upload_to='galeri/cover/', validators=[sekolah.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=sekolah.models.ubah_nama_gambar_acak, validators=[sekolah.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=sekolah.models.ubah_nama_poster_event, validators=[sekolah.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='fotoalbum',
            name='gambar',
            field=models.ImageField(upload_to=sekolah.models.ubah_nama_foto_album, validators=[sekolah.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='guru',
            name='foto',
            field=models.ImageField(blank=True, default='default-profile/profile-picture.png', null=True, upload_to=sekolah.models.ubah_nama_foto_sdm, validators=[sekolah.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='guru',
            name='motto',
            field=models.TextField(blank=True, help_text='Motto atau kutipan kerja', null=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', validators=[sekolah.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='lampiran',
            field=models.FileField(blank=True, help_text='File lampiran PDF (opsional)', null=True, upload_to=sekolah.models.ubah_nama_file_pengumuman, validators=[sekolah.models.validate_pdf_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=sekolah.models.ubah_nama_foto_post, validators=[sekolah.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_profil',
            field=models.ImageField(blank=True, default='default/profile-picture.png', help_text='Foto profil akun (avatar)', null=True, upload_to=sekolah.models.ubah_nama_foto_profil, validators=[sekolah.models.validate_image_extension]),
        ),
    ]
