# Generated by Django 6.0.7 on 2026-08-09 06:16

import sekolah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0020_alter_albumgaleri_cover_alter_berita_gambar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto_profil',
            field=models.ImageField(blank=True, default='default/profile-picture.png', help_text='Foto profil akun (avatar)', null=True, upload_to=sekolah.models.ubah_nama_foto_profil, validators=[sekolah.models.validate_image_extension]),
        ),
    ]
