# Generated by Django 6.0.7 on 2026-08-09 06:45

import sekolah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0022_alter_guru_foto_alter_userprofile_foto_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='foto',
            field=models.ImageField(blank=True, default='default-profile/profile-picture.png', null=True, upload_to=sekolah.models.ubah_nama_foto_sdm, validators=[sekolah.models.validate_image_extension]),
        ),
    ]
