# Generated by Django 6.0.7 on 2026-08-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0023_alter_guru_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uuid_code',
            field=models.CharField(blank=True, help_text='Kode UUID unik 6 angka random untuk presensi digital', max_length=6, null=True, unique=True),
        ),
    ]
