# Generated by Django 6.0.7 on 2026-08-09 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0024_userprofile_uuid_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waktu_scan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Hadir Tepat Waktu', 'Hadir Tepat Waktu'), ('Terlambat', 'Terlambat')], default='Hadir Tepat Waktu', max_length=50)),
                ('peran', models.CharField(default='Guru', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_presensi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presensi Kehadiran',
                'verbose_name_plural': 'Data Riwayat Presensi',
                'ordering': ['-waktu_scan'],
            },
        ),
    ]
