# Generated by Django 6.0.7 on 2026-08-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0025_presensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='waktu_pulang',
            field=models.DateTimeField(blank=True, help_text='Waktu scan pulang', null=True),
        ),
    ]
