# Generated by Django 6.0.7 on 2026-08-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0026_presensi_waktu_pulang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='waktu_pulang',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
